Fix TS example error.
Raw error message:
$ cd /Users/hokeunkim/Development/eclipses/lingua-franca-master/git/lingua-franca/example/TS/src-gen/HTTPSRequestReactor/HTTPSRequest
Hokeuns-MBP:HTTPSRequest hokeunkim$ bash --login -c npm run check-types

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /Users/hokeunkim/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.14.13 /usr/local/lib/node_modules/npm
Hokeuns-MBP:HTTPSRequest hokeunkim$ npm run check-types

> LinguaFrancaDefault@0.0.1 check-types /Users/hokeunkim/Development/eclipses/lingua-franca-master/git/lingua-franca/example/TS/src-gen/HTTPSRequestReactor/HTTPSRequest
> tsc

src/HTTPSRequest.ts:197:26 - error TS2339: Property 'requestShutdown' does not exist on type 'UtilityFunctions'.

197                     util.requestShutdown();
                             ~~~~~~~~~~~~~~~

Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! LinguaFrancaDefault@0.0.1 check-types: `tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the LinguaFrancaDefault@0.0.1 check-types script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hokeunkim/.npm/_logs/2021-07-12T05_50_56_732Z-debug.log